sudo: required

language: c#

services:
  - docker

env:
  - TEST_SUITE=Unit
  - TEST_SUITE=Integration

install:
  - git checkout $TRAVIS_BRANCH
  - sh prepare.sh
  - sh init.sh
  - git remote set-url origin https://${GHTOKEN}@github.com/CompulsiveCoder/gitter-cs.git

script:
  - sh test-and-graduate.sh
